# docker-compose.yml
version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports: ["8000:8000"]
    env_file: [.env]
    volumes:
      - ./storage:/app/storage
      - ./policies:/app/policies
  web:
    image: nginx:alpine
    ports: ["8080:80"]
    volumes:
      - ./frontend:/usr/share/nginx/html:ro